plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.3'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = "oi.reader"
version = "1.0-SNAPSHOT"

java {
    sourceCompatibility = '21'
}

springBoot {
    mainClass = 'oi.reader.Main'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
}

tasks.test {
    useJUnitPlatform()
}